import type { Metadata } from "next";
import "./globals.css";
import { MediaQueryProvider } from "@/context/MediaQueryContext";
import NavbarWrapper from "@/components/NavbarWrapper";
import BottomNavWrapper from "@/components/BottomNavWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MediaQueryProvider>
          <NavbarWrapper />
          <BottomNavWrapper>
            {children}
          </BottomNavWrapper>
        </MediaQueryProvider>
      </body>
    </html>
  );
}
